Repository oddhus/PollApplication-Frontend, pull requests merged in 2020-10, with the labels that each got.

#17 Feat/account page and landing page
  package.json
  public/index.html
  src/components/AccountPage/EditEmail.js
  src/components/AccountPage/EditPassword.js
  src/components/AlertDialog.js
  src/components/Navbar.js
  src/components/StatusBar.js
  src/pages/AccountPage.js
  src/pages/LandingPage.js
  src/tests/AccountPage.test.js
  src/theme/theme.js
  yarn.lock
Labels: Ready to merge

#20 Feat/mock auth
  package.json
  src/App.js
  src/components/Navbar.js
  src/data/use-user.js
  src/mock/api-user.js
  src/mock/auth.js
  src/pages/AccountPage.js
  yarn.lock
Labels: Ready to merge

#19 Feature/login page
  .gitignore
  package.json
  src/App.js
  src/components/ThemeButton.js
  src/components/ThemeCircularProgress.js
  src/pages/LoginPage.js
  yarn.lock
Labels: Ready to merge

#26 Page/sign up
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
Labels: Ready to merge

#23 Feat/create edit poll page
  src/components/DurationPicker.js
  src/pages/CreateEditPollPage.js
  src/routes/routes.js
  src/utils/calculateTime.js
Labels: Ready to merge, enhancement

#22 Feat/vote page
  src/pages/VotePage.js
Labels: Ready to merge, enhancement

#27 Feat/user polls page
  package.json
  src/components/AlertDialog.js
  src/components/DangerButton.js
  src/components/PollItem.js
  src/components/PollList.js
  src/components/ResultChart.js
  src/components/ResultModal.js
  src/components/ThemeButton.js
  src/pages/AccountPage.js
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/pages/UserPollsPage.js
  src/utils/categorizePolls.js
  yarn.lock
Labels: work in progress

#28 Feat/connect login, register, my polls, results and my account to backend
  package.json
  src/App.js
  src/components/AccountPage/EditPassword.js
  src/components/Navbar.js
  src/components/PollItem.js
  src/components/PollList.js
  src/components/ResultChart.js
  src/data/use-user.js
  src/index.js
  src/mock/api-user.js
  src/mock/auth.js
  src/pages/AccountPage.js
  src/pages/CreateEditPollPage.js
  src/pages/LoginPage.js
  src/pages/RegisterPage.js
  src/pages/ResultPage.js
  src/pages/UserPollsPage.js
  src/queries/use-mypolls.js
  src/queries/use-pollresults.js
  src/queries/use-user.js
  src/utils/categorizePolls.js
  yarn.lock
Labels: Ready to merge

#25 Finished no match page
  public/index.html
  src/App.js
  src/components/Tile.js
  src/pages/NoMatch.js
  src/routes/routes.js
Labels: enhancement, work in progress

#29 feat/connect vote to backend
  src/components/PollItem.js
  src/pages/CreateEditPollPage.js
  src/pages/LandingPage.js
  src/pages/ResultPage.js
  src/pages/VotePage.js
  src/queries/use-pollinfo.js
  src/utils/categorizePolls.js
Labels: Ready to merge

#30 Feat/admin page
  package.json
  src/components/AdminPage/PaginationButtons.js
  src/components/AdminPage/PollActiveFilterButtons.js
  src/components/AdminPage/Table.js
  src/components/AlertDialog.js
  src/components/EditUserDialog.js
  src/components/Tile.js
  src/pages/AdminPage.js
  src/pages/CreateEditPollPage.js
  src/pages/UserPollsPage.js
  src/routes/routes.js
  src/utils/calculateTime.js
  src/utils/categorizePolls.js
  src/utils/tableUtils.js
Labels: Ready to merge
